import type { Catalogue, CatalogueEntry } from "@/domain/assets/catalogue";
import { chooseModel, distortion } from "@/domain/assets/choice";
import { MODEL_TUNING } from "@/domain/assets/model-tuning";
import { FurnitureCategory } from "@/domain/schemas/design";
import CATALOGUE_JSON from "./asset-catalogue.json";
import { MODEL_IDS, TEXTURE_IDS } from "./asset-ids";

/**
 * Every asset in public/, generated by scripts/fetch-assets.mjs from
 * assets/manifest/*.json (validated by assets.test.ts).
 */
export const ASSET_CATALOGUE = CATALOGUE_JSON as unknown as Catalogue;

export type ModelId = (typeof MODEL_IDS)[number];
export type TextureId = (typeof TEXTURE_IDS)[number];

/** A model's picture for cards and pickers: rendered by the asset pipeline, or the source's own preview until then. */
export function modelPicture(id: string): string | undefined {
  const e = ASSET_CATALOGUE[id];
  return e?.kind === "model" ? (e.render ?? e.thumb) : e?.thumb;
}

/** One value per id of a kind, read from its catalogue row. */
function table<Id extends string, K extends CatalogueEntry["kind"], V>(ids: readonly Id[], kind: K, value: (e: Extract<CatalogueEntry, { kind: K }>) => V): Readonly<Record<Id, V>> {
  const out = {} as Record<Id, V>;
  for (const id of ids) {
    const e = ASSET_CATALOGUE[id];
    if (e?.kind === kind) out[id] = value(e as Extract<CatalogueEntry, { kind: K }>);
  }
  return out;
}

/** Native size of each model in public/models, in cm as [w, h, d]. */
export const MODEL_SIZE = table(MODEL_IDS, "model", (e): readonly [number, number, number] => e.size);

export interface PieceModel extends ModelVariant {
  /** Style keys from the manifest tags, e.g. "japandi". */
  styles: readonly string[];
  /** Material names that are upholstery, tinted to the piece's colour. */
  fabric?: RegExp;
}

/**
 * The real models for each catalogue category, from the manifest tags
 * ("furniture.sofa", "style.japandi"). Files live in public/ and are fetched by
 * scripts/fetch-assets.mjs. Every model is stretched to exactly the piece's
 * w × h × d; chooseModel picks the default among several.
 */
export const PIECE_MODELS: Readonly<Record<FurnitureCategory, readonly PieceModel[]>> = (() => {
  const out = Object.fromEntries(FurnitureCategory.options.map((c) => [c, [] as PieceModel[]])) as Record<FurnitureCategory, PieceModel[]>;
  for (const id of MODEL_IDS) {
    const tags = ASSET_CATALOGUE[id]!.tags;
    const styles = tags.filter((t) => t.startsWith("style.")).map((t) => t.slice(6));
    for (const t of tags) {
      const c = FurnitureCategory.safeParse(t.replace(/^furniture\./, ""));
      if (t.startsWith("furniture.") && c.success) out[c.data].push({ id, styles, ...MODEL_TUNING[id] });
    }
  }
  return out;
})();

/**
 * Categories that also have a version assembled in code from real PBR
 * textures (three/pieces.tsx). It matches the size by construction and takes
 * the piece's colour everywhere; categories without models always use it.
 */
export const BUILT_CATEGORIES: ReadonlySet<FurnitureCategory> = new Set([
  "sofa",
  "bed",
  "wardrobe",
  "dresser",
  "storage",
  "shoe_cabinet",
  "bookshelf",
  "desk",
  "dining_table",
  "bench",
  "rug",
  "floor_lamp",
  "mirror",
  "wall_shelf",
  "coat_rack",
  "other",
]);

/** `modelId` value that asks for the version built in code. */
export const BUILT_MODEL = "built";

/**
 * How a piece is drawn: the model the user chose if it belongs to the
 * category, "built" when they asked for it (or there is no model), else the
 * model that fits the size and the style profile best.
 */
export function pieceModel(
  category: FurnitureCategory,
  modelId: string | undefined,
  w: number,
  d: number,
  h: number,
  scores: Readonly<Partial<Record<string, number>>> | null,
): PieceModel | typeof BUILT_MODEL {
  const options = PIECE_MODELS[category];
  if (modelId === BUILT_MODEL && BUILT_CATEGORIES.has(category)) return BUILT_MODEL;
  const chosen = options.find((o) => o.id === modelId);
  if (chosen) return chosen;
  if (options.length === 0) return BUILT_MODEL;
  const best = chooseModel(
    options.map((o) => ({ ...o, size: nativeFootprint(o) })),
    w,
    d,
    h,
    scores,
  );
  // A model this far from the piece's proportions would look squashed; the built version fits.
  if (BUILT_CATEGORIES.has(category) && distortion(best.size, w, d, h) > MAX_DEFAULT_DISTORTION) return BUILT_MODEL;
  return best;
}

/** About a 2.7× stretch between two axes: beyond it the default falls back to the built version. */
export const MAX_DEFAULT_DISTORTION = 1;

export interface ModelVariant {
  id: ModelId;
  /** Degrees to turn the model so its front faces +z (the piece's front). */
  turn?: number;
}

/** A variant's native [w, h, d] after its turn (a quarter turn swaps width and depth). */
export function nativeFootprint(v: ModelVariant): [number, number, number] {
  const [w, h, d] = MODEL_SIZE[v.id];
  return Math.round((v.turn ?? 0) / 90) % 2 ? [d, h, w] : [w, h, d];
}

/** PBR texture sets in public/textures/<id>/: the real-world size one tile covers, in cm. */
export const TEXTURE_CM = table(TEXTURE_IDS, "texture", (e) => e.tileCm);

/** Mean sRGB colour of each diffuse map, so a tint can land on a target colour. */
export const TEXTURE_MEAN = table(TEXTURE_IDS, "texture", (e): readonly [number, number, number] => e.mean);
