// Generated by scripts/fetch-assets.mjs from asset-catalogue.json. Do not edit.
export const MODEL_IDS = ["dining_chair_02","door_with_frame_witnessk","handle_knob","handle_lever_classic","handle_lever_modern","handle_pull","hanging_picture_frame_02","kenney_toilet","modern_arm_chair_01","modern_coffee_table_01","modern_wooden_cabinet","painted_wooden_chair_01","potted_plant_01","potted_plant_02","radiator_valve_trv","sheen_wood_leather_sofa","side_table_01"] as const;
export const TEXTURE_IDS = ["acg_plaster_001","laminate_floor_02","oak_veneer_01","plastered_wall_04","poly_wool_herringbone","terracotta_floor_tiles","wood_floor"] as const;
export const HDRI_IDS = ["kloofendal_48d_partly_cloudy_puresky"] as const;
