import type { DesignContent } from "@/domain/schemas/design";

/**
 * Hand-made design for the sample "Living room" (420 × 380 cm, door on the
 * bottom wall at the right, two windows and a radiator on the top wall).
 * It passes the validator with zero errors and includes the family preset's
 * must-keep sideboard. Used by the dev "Insert sample design" button, unit
 * tests and E2E, so the UI can be tested without API cost.
 */
export const SAMPLE_DESIGN: DesignContent = {
  concept: {
    title: "Warm Nordic living room",
    summary:
      "A calm, light base of warm white walls and oak with a sage secondary and terracotta accents. The sofa faces the media wall; the existing sideboard anchors the wall by the door. Trends live only in cushions and the throw.",
  },
  zones: [
    { id: "relax", name: "Lounge", purpose: "relax", rect: { x: 0, y: 90, w: 260, d: 240 }, rationale: "Sofa, rug and coffee table form one conversation area." },
    { id: "media", name: "Media wall", purpose: "relax", rect: { x: 380, y: 100, w: 40, d: 180 }, rationale: "TV unit on the wall with the TV socket." },
  ],
  furniture: [
    {
      id: "sofa",
      category: "sofa",
      name: "3-seat sofa",
      placement: "floor",
      w: 220,
      d: 95,
      h: 85,
      x: 48,
      y: 210,
      rotation: 270,
      elevation: 0,
      zoneId: "relax",
      material: "Wool blend upholstery, oak legs",
      colorHex: "#BEB5A7",
      paletteRole: "neutral",
      price: { min: 1200, max: 1800, currency: "EUR" },
      productQuery: "3-Sitzer Sofa Wollstoff greige 220 cm",
      investmentTier: "anchor",
      trendRisk: 0.15,
      renterFriendly: true,
      requiresDrilling: false,
      existing: false,
      rationale: "Timeless shape in a durable, washable-cover fabric that suits kids and a dog.",
    },
    {
      id: "coffee-table",
      category: "coffee_table",
      name: "Oak coffee table",
      placement: "floor",
      w: 110,
      d: 55,
      h: 40,
      x: 168,
      y: 210,
      rotation: 270,
      elevation: 0,
      zoneId: "relax",
      material: "Solid oak, oiled",
      colorHex: "#C19A6B",
      paletteRole: "base",
      price: { min: 200, max: 350, currency: "EUR" },
      productQuery: "Couchtisch Eiche massiv 110 x 55",
      investmentTier: "mid",
      trendRisk: 0.1,
      renterFriendly: true,
      requiresDrilling: false,
      existing: false,
      rationale: "45 cm from the sofa: within reach, still easy to pass.",
    },
    {
      id: "tv-unit",
      category: "tv_unit",
      name: "Low TV sideboard",
      placement: "floor",
      w: 180,
      d: 40,
      h: 50,
      x: 400,
      y: 190,
      rotation: 90,
      elevation: 0,
      zoneId: "media",
      material: "Oak veneer",
      colorHex: "#C19A6B",
      paletteRole: "base",
      price: { min: 300, max: 500, currency: "EUR" },
      productQuery: "TV Lowboard Eiche 180 cm",
      investmentTier: "mid",
      trendRisk: 0.15,
      renterFriendly: true,
      requiresDrilling: false,
      existing: false,
      rationale: "Placed at the TV socket and clear of the door swing.",
    },
    {
      id: "rug",
      category: "rug",
      name: "Wool rug 160 × 240",
      placement: "floor_covering",
      w: 240,
      d: 160,
      h: 1,
      x: 180,
      y: 210,
      rotation: 270,
      elevation: 0,
      zoneId: "relax",
      material: "Hand-woven wool",
      colorHex: "#E6DCCB",
      paletteRole: "base",
      price: { min: 250, max: 400, currency: "EUR" },
      productQuery: "Wollteppich 160x240 naturweiß",
      investmentTier: "mid",
      trendRisk: 0.2,
      renterFriendly: true,
      requiresDrilling: false,
      existing: false,
      rationale: "Warms the floor in a long heating season and zones the lounge.",
    },
    {
      id: "floor-lamp",
      category: "floor_lamp",
      name: "Linen floor lamp",
      placement: "floor",
      w: 40,
      d: 40,
      h: 160,
      x: 30,
      y: 50,
      rotation: 0,
      elevation: 0,
      material: "Linen shade, brass",
      colorHex: "#F4EFE6",
      paletteRole: "base",
      price: { min: 120, max: 200, currency: "EUR" },
      productQuery: "Stehleuchte Leinenschirm",
      investmentTier: "swappable",
      trendRisk: 0.2,
      renterFriendly: true,
      requiresDrilling: false,
      existing: false,
      rationale: "Reading light next to the sofa, beside the window without blocking it.",
    },
    {
      id: "plant",
      category: "plant",
      name: "Fiddle-leaf fig",
      placement: "floor",
      w: 45,
      d: 45,
      h: 120,
      x: 397,
      y: 60,
      rotation: 0,
      elevation: 0,
      material: "Ceramic pot",
      colorHex: "#7A7D4A",
      paletteRole: "secondary",
      price: { min: 40, max: 80, currency: "EUR" },
      investmentTier: "swappable",
      trendRisk: 0.3,
      renterFriendly: true,
      requiresDrilling: false,
      existing: false,
      rationale: "Green corner in bright light, clear of both windows.",
    },
    {
      id: "sideboard",
      category: "sideboard",
      name: "Grandma's sideboard",
      placement: "floor",
      w: 160,
      d: 45,
      h: 85,
      x: 180,
      y: 357.5,
      rotation: 180,
      elevation: 0,
      material: "Walnut",
      colorHex: "#5C4033",
      paletteRole: "neutral",
      price: { min: 0, max: 0, currency: "EUR" },
      investmentTier: "anchor",
      trendRisk: 0.1,
      renterFriendly: true,
      requiresDrilling: false,
      existing: true,
      rationale: "The family piece gets the wall facing the lounge, clear of the door.",
    },
    {
      id: "art",
      category: "art",
      name: "Framed print",
      placement: "wall",
      w: 100,
      d: 3,
      h: 70,
      x: 1.5,
      y: 210,
      rotation: 270,
      elevation: 140,
      material: "Oak frame",
      colorHex: "#C0683F",
      paletteRole: "accent",
      price: { min: 60, max: 150, currency: "EUR" },
      investmentTier: "swappable",
      trendRisk: 0.4,
      renterFriendly: true,
      requiresDrilling: true,
      existing: false,
      rationale: "Centred above the sofa; two dowel holes in plaster are fine for renters.",
    },
  ],
  palette: {
    base: { name: "Warm white", hex: "#F4EFE6", paint: { system: "RAL", code: "9010" }, share: 0.6, usage: ["walls", "ceiling", "rug"] },
    secondary: { name: "Sage", hex: "#A3B09A", paint: { system: "NCS", code: "S 3010-G30Y" }, share: 0.3, usage: ["plant", "throw", "curtains"] },
    accent: { name: "Terracotta", hex: "#C0683F", paint: { system: "none" }, share: 0.1, usage: ["cushions", "art"] },
    rationale: "Warm white offsets cool north light; sage links to the plants; terracotta adds warmth in small doses.",
  },
  surfaces: [
    {
      surface: "walls",
      material: "Washable matt emulsion",
      finish: "matt",
      colorHex: "#F4EFE6",
      paint: { system: "RAL", code: "9010" },
      trendRisk: 0.05,
      renterFriendly: true,
      price: { min: 120, max: 200, currency: "EUR" },
      rationale: "Light, neutral and easy to return at move-out.",
    },
    {
      surface: "floor",
      material: "Existing oak parquet",
      finish: "oiled",
      colorHex: "#C19A6B",
      trendRisk: 0.05,
      renterFriendly: true,
      rationale: "Kept as is; the rug protects it.",
    },
  ],
  lighting: [
    {
      id: "pendant",
      layer: "ambient",
      fixture: "Paper pendant 60 cm",
      mount: "ceiling",
      position: { x: 210, y: 190 },
      colorTempK: 2700,
      lumens: 1500,
      dimmable: true,
      requiresDrilling: false,
      price: { min: 80, max: 150, currency: "EUR" },
      trendRisk: 0.2,
      rationale: "Uses the existing ceiling outlet; soft general light.",
    },
    {
      id: "reading",
      layer: "task",
      fixture: "Floor lamp",
      mount: "floor",
      itemId: "floor-lamp",
      colorTempK: 2700,
      lumens: 800,
      dimmable: true,
      requiresDrilling: false,
      price: { min: 120, max: 200, currency: "EUR" },
      trendRisk: 0.2,
      rationale: "Reading light at the sofa end.",
    },
    {
      id: "led-strip",
      layer: "accent",
      fixture: "LED strip behind TV unit",
      mount: "under_cabinet",
      colorTempK: 2400,
      lumens: 300,
      dimmable: true,
      requiresDrilling: false,
      price: { min: 30, max: 60, currency: "EUR" },
      trendRisk: 0.3,
      rationale: "Glow behind the TV reduces eye strain in the evening.",
    },
  ],
  textiles: [
    { id: "curtains", type: "curtain", material: "Linen", colorHex: "#A3B09A", paletteRole: "secondary", size: "2 × 140 × 250 cm", price: { min: 120, max: 200, currency: "EUR" }, trendRisk: 0.2, rationale: "Softens the windows, keeps heat in during winter." },
    { id: "cushions", type: "cushion", material: "Bouclé", colorHex: "#C0683F", paletteRole: "accent", size: "3 × 50 × 50 cm", price: { min: 60, max: 100, currency: "EUR" }, trendRisk: 0.7, rationale: "The trend piece: cheap to swap in two years." },
    { id: "throw", type: "throw", material: "Wool", colorHex: "#A3B09A", paletteRole: "secondary", price: { min: 50, max: 90, currency: "EUR" }, trendRisk: 0.3, rationale: "Extra warmth for winter evenings." },
  ],
  longevity: {
    summary: "Sofa, sideboard, floor and wall colour are timeless; the bouclé cushions and the print carry the trends and are cheap to replace.",
    trendItems: ["cushions", "art"],
  },
};

/** The same design with deliberate problems: coffee table pushed into the sofa, plant in the door swing. */
export const SAMPLE_DESIGN_BROKEN: DesignContent = {
  ...SAMPLE_DESIGN,
  concept: { ...SAMPLE_DESIGN.concept, title: "Broken sample (for testing the validator)" },
  furniture: SAMPLE_DESIGN.furniture.map((f) =>
    f.id === "coffee-table" ? { ...f, x: 110 } : f.id === "plant" ? { ...f, x: 350, y: 350 } : f,
  ),
};

export const SAMPLE_DESIGNS: readonly DesignContent[] = [SAMPLE_DESIGN, SAMPLE_DESIGN_BROKEN];
