import { assetPaths, type Catalogue } from "../../src/domain/assets/catalogue.ts";
import type { ManifestEntry } from "../../src/domain/assets/manifest.ts";

/** Public paths an entry's processing produces (thumbnail aside). */
export function outputsOf(e: Pick<ManifestEntry, "id" | "kind">): string[] {
  if (e.kind === "model") return [assetPaths.model(e.id)];
  if (e.kind === "texture") return assetPaths.texture(e.id);
  return [assetPaths.hdri(e.id)];
}

/** Public asset files that no manifest entry produces. */
export function orphans(files: readonly string[], entries: readonly ManifestEntry[]): string[] {
  const wanted = new Set(entries.flatMap((e) => [...outputsOf(e), assetPaths.thumb(e.id)]));
  return files.filter((f) => !wanted.has(f));
}

/** Catalogue rows for ids still in the manifest, sorted by id so diffs stay small. */
export function mergeCatalogue(old: Catalogue, fresh: Catalogue, entries: readonly ManifestEntry[]): Catalogue {
  const ids = entries.map((e) => e.id).sort();
  const out: Catalogue = {};
  for (const id of ids) {
    const row = fresh[id] ?? old[id];
    if (row) out[id] = row;
  }
  return out;
}

/**
 * TypeScript source listing the catalogue's ids per kind, so the app can type
 * model and texture ids (a JSON import only knows `kind: string`).
 */
export function idsModule(catalogue: Catalogue): string {
  const ids = (kind: string) => Object.keys(catalogue).filter((id) => catalogue[id]!.kind === kind);
  const list = (name: string, kind: string) => `export const ${name} = ${JSON.stringify(ids(kind))} as const;\n`;
  return `// Generated by scripts/fetch-assets.mjs from asset-catalogue.json. Do not edit.\n${list("MODEL_IDS", "model")}${list("TEXTURE_IDS", "texture")}${list("HDRI_IDS", "hdri")}`;
}
